### PR TITLE
macOS support, fix #9, function parameters

### LINKED ISSUE #9: Crashes on Ghidra 10.0.1
It takes the tool and project manager down too, no ghidra windows survive

### PR DESCRIPTION
**Pull request by nneonneo**
This patchset introduces a few fixes and improvements to ghidra2dwarf:

- Added macOS support by compiling libdwarf-20200719 as a shared library
- Added a status message so that progress is more obvious on large binaries with many functions
- Eliminated a redundant call to `get_decompiled_function` to cut down on script execution time
- Generate `formal_parameter` tags for function parameters to improve backtraces and debugging experience
- Fix Java crash reported in #9 by using `defaultFieldName` if `fieldName` is not available (the segfault is caused by a segfault from passing a NULL pointer through to a `libdwarf` function).

### CODE REVIEW

**Comment by NextLight** [comment]
Hey, thank you so much for your contribution, we appreciate it!

We would like to avoid distributing binaries from untrusted (a.k.a. not us) sources.  
I'm going to merge this PR, but I will revert the Mac OS support immediately after. I apologize for the inconvenience.

We plan to build libdwarf automatically via CI and hopefully it will happen very soon™ (likely today), so this should fix that issue for good.

On a side note, you probably have noticed that the code is horrible (mostly because it never exited the prototype phase).  
I'm working on a big refactor (a.k.a. I've rewritten everything) to make it nicer and a lot faster, so please keep that in mind if you were planning to make big changes to it in the near future.

**Comment by nneonneo** [comment]
Thank you! I understand the concern about the untrusted binary - makes sense. I am looking forward to the rewrite - this project is *immensely* useful in its current state already.

**Comment by meowmeowxw** [comment]
We started working today on the CI for compiling libdwarf in a cross-platform way on https://github.com/cesena/libdwarf-ghidra2dwarf, so it will be available soon hopefully :) thank you for your support!

**Comment by NextLight** [comment]
453bb3d3bcdc3a6172c91cfe69dd6e196497a866 should have officially added macOS support.  
I don't have a mac to test this with, however I've extended the tests to run on macOS as well and they seem to pass.

Please let us know if you have trouble with it!

**Comment by nneonneo** [comment]
Fantastic! I pulled the new changes and tested with macOS Ghidra - works like a charm.

**Pull request merged**
