### PR TITLE
Add ELF exporting logic.

### PR DESCRIPTION
**Pull request by Manouchehri**
Solves #13.

### CODE REVIEW

**Comment by Manouchehri** [comment]
ping @meowmeowxw @nneonneo @NextLight

**Comment by nneonneo** [comment]
To be honest, I'm a bit leery of this. The Ghidra ElfExporter has had some serious bugs; https://github.com/NationalSecurityAgency/ghidra/issues/19 tracks issues that it's had since the beginning. Although I hope the issues have been fixed, I'd like to know if you've run into any issues with the exporter? In particular, I would like to know if the exporter changes *anything* compared to the on-disk file.

**Comment by Manouchehri** [comment]
We haven't run into issues yet, but we also haven't been looking for them.

https://github.com/NationalSecurityAgency/ghidra/issues/19#issuecomment-805751736

**Comment by nneonneo** [comment]
FWIW, we tried out ELF export this weekend on 10.3 (not specifically this PR, just the Ghidra feature) and wound up with executables that didn’t work properly. We haven’t debugged in detail what went wrong yet.

**Comment by Manouchehri** [comment]
Closing in favour of #24.

**Pull request closed without merging**
